// lib/articles/dlya-rebenka.js
export default {
  slug: "dlya-rebenka",
  category_key: "guide",
  read_minutes: 5,
  cover_url: null,
  title: {
    ru: "Домбра для ребёнка: с чего начать",
    kz: "Балаға арналған домбыра: неден бастау керек",
    en: "A dombra for a child: where to start",
    tr: "Çocuk için dombra: nereden başlamalı",
  },
  excerpt: {
    ru: "Какой размер брать, почему торопиться не стоит и как бесплатный тренажёр помогает заниматься без педагога рядом.",
    kz: "Қандай өлшем алу керек, неге асықпаған жөн және тегін тренажёр мұғалімсіз айналысуға қалай көмектеседі.",
    en: "Which size to pick, why there's no need to rush, and how the free trainer helps practice without a teacher present.",
    tr: "Hangi ölçü seçilmeli, neden acele etmemeli ve ücretsiz eğitim aracı bir öğretmen olmadan çalışmaya nasıl yardımcı olur.",
  },
  content: {
    ru: [
      { type: "p", text: "Домбра часто становится первым музыкальным инструментом в жизни казахстанского ребёнка — и здесь легко наделать ошибок из лучших побуждений: купить инструмент «на вырост», перегрузить занятиями с первого дня или выбрать слишком сложный кюй. Разберём, с чего действительно стоит начать." },
      { type: "h2", text: "Не берите инструмент «на вырост»" },
      { type: "p", text: "Соблазн купить домбру побольше, чтобы «хватило на дольше», встречается часто — но для ребёнка это скорее вредно. Слишком крупный корпус и широкий гриф делают игру физически неудобной: пальцы не дотягиваются до ладов, инструмент тяжело держать. Для детей до 10–12 лет обычно подходит размер 42 — самый компактный из тех, что есть в каталоге." },
      { type: "h2", text: "Первые недели — про интерес, не про технику" },
      { type: "p", text: "Задача первого месяца — не выучить сложный кюй, а не отбить желание заниматься. Простые повторяющиеся мелодии, которые быстро получаются, работают лучше, чем правильная, но скучная методика. Ребёнок, которому нравится звук, который у него получается, сам захочет взять инструмент снова." },
      { type: "h2", text: "Тренажёр — помощник, когда взрослого нет рядом" },
      { type: "p", text: "Не всегда у родителя есть время сидеть рядом и следить за каждым движением. Бесплатный тренажёр на dombyra.kz показывает, куда ставить пальцы, в собственном темпе ребёнка — можно замедлить почти вдвое и повторять сложный момент, сколько нужно. Караоке-режим при этом слушает игру через микрофон и подсвечивает, если нота получилась не той — ребёнок сам видит свой прогресс, без необходимости, чтобы кто-то стоял рядом и поправлял." },
      { type: "h2", text: "Домбра должна быть настроена — и это тоже забота ребёнка" },
      { type: "p", text: "Расстроенный инструмент приучает слух к неправильной высоте звука, даже если ребёнок пока не может объяснить, что именно не так. Приучите с самого начала: сначала тюнер, потом занятие. У нас на сайте тюнер тоже бесплатный, работает через микрофон — с ним справится и ребёнок самостоятельно, после пары показов." },
      { type: "h2", text: "Не сравнивайте с другими" },
      { type: "p", text: "Скорость прогресса у детей сильно различается, и это нормально. Кюй, который один ребёнок разучивает за неделю, другому может понадобиться месяц — и это не говорит о способностях, просто разный темп. Фокус на регулярности небольших занятий работает лучше, чем редкие, но долгие «рывки»." },
    ],
    kz: [
      { type: "p", text: "Домбыра көбіне қазақстандық баланың өміріндегі алғашқы музыкалық аспабына айналады — және осы жерде жақсы ниетпен жасалатын қателер жиі кездеседі: аспапты «өсуіне қарай» алу, бірінші күннен сабақпен шамадан тыс жүктеу немесе тым күрделі күй таңдау. Нақты неден бастау керегін қарастырайық." },
      { type: "h2", text: "Аспапты «өсуіне қарай» алмаңыз" },
      { type: "p", text: "«Ұзағырақ жетсін» деп үлкенірек домбыра алу қызығушылығы жиі кездеседі — бірақ бала үшін бұл керісінше зиянды. Тым үлкен корпус пен кең гриф ойнауды физикалық тұрғыдан ыңғайсыз етеді: саусақтар пернелерге жетпейді, аспапты ұстау қиын болады. 10–12 жасқа дейінгі балаларға әдетте 42 өлшем жарайды — каталогтағы ең ықшамы." },
      { type: "h2", text: "Алғашқы апталар — қызығушылық туралы, техника туралы емес" },
      { type: "p", text: "Бірінші айдың міндеті — күрделі күй үйрену емес, айналысуға деген ықыласты өшірмеу. Тез шығатын қарапайым, қайталанатын әуендер дұрыс, бірақ жалықтыратын әдістемеден гөрі жақсы жұмыс істейді. Өзінен шыққан дыбысқа риза болған бала аспапты өзі қайта алғысы келеді." },
      { type: "h2", text: "Тренажёр — үлкен адам жанында жоқ кезде көмекші" },
      { type: "p", text: "Ата-анада әрдайым жанында отырып, әр қимылды бақылауға уақыт бола бермейді. dombyra.kz-тегі тегін тренажёр саусақты қайда қою керегін баланың өз қарқынымен көрсетеді — екі есе дерлік баяулатып, қажет болғанша қайталауға болады. Ал караоке режимі ойынды микрофон арқылы тыңдап, нота қате шыққанда көрсетеді — бала өзінің прогресін көреді, жанында тұрып түзетіп отыратын адамның қажеті жоқ." },
      { type: "h2", text: "Домбыра бұралған болуы керек — бұл да баланың міндеті" },
      { type: "p", text: "Бұрауы кеткен аспап құлақты дұрыс емес дыбыс биіктігіне үйретеді, бала бұл дәл не екенін түсіндіре алмаса да. Бастан-ақ дағды қалыптастырыңыз: алдымен тюнер, содан кейін сабақ. Біздің сайтта тюнер де тегін, микрофон арқылы жұмыс істейді — оны бала бірнеше рет көрсеткеннен кейін өзі меңгереді." },
      { type: "h2", text: "Басқалармен салыстырмаңыз" },
      { type: "p", text: "Балалардың прогресс жылдамдығы әртүрлі болады, және бұл қалыпты жағдай. Бір бала апта ішінде үйренетін күйге екінші балаға бір ай керек болуы мүмкін — бұл қабілетсіздік емес, жай ғана қарқын әртүрлі. Сирек, бірақ ұзақ «серпілістерден» гөрі шағын сабақтардың тұрақтылығына назар аудару жақсырақ нәтиже береді." },
    ],
    en: [
      { type: "p", text: "The dombra is often the first musical instrument in a Kazakhstani child's life — and it's easy to make well-meaning mistakes: buying an instrument \"to grow into,\" overloading the first days with lessons, or picking a kui that's too advanced. Let's look at what's actually worth starting with." },
      { type: "h2", text: "Don't buy an instrument \"to grow into\"" },
      { type: "p", text: "It's tempting to buy a bigger dombra so it \"lasts longer\" — but for a child that usually backfires. A body that's too large and a wide neck make playing physically awkward: fingers can't reach the frets, the instrument is hard to hold. For children under 10–12, size 42 usually works well — the most compact option in the catalog." },
      { type: "h2", text: "The first weeks are about interest, not technique" },
      { type: "p", text: "The goal of the first month isn't to learn a difficult kui — it's not to kill the motivation to keep practicing. Simple, repetitive melodies that come together quickly work better than a technically correct but boring method. A child who likes the sound they're making will want to pick up the instrument again on their own." },
      { type: "h2", text: "The trainer helps when an adult isn't around" },
      { type: "p", text: "Parents don't always have time to sit and watch every movement. The free trainer on dombyra.kz shows where to place fingers at the child's own pace — you can slow it down by almost half and repeat a tricky part as many times as needed. The karaoke mode listens through the microphone and highlights wrong notes — the child sees their own progress without needing someone standing over them correcting every move." },
      { type: "h2", text: "The dombra needs to be in tune — that's the child's job too" },
      { type: "p", text: "An out-of-tune instrument trains the ear to a wrong pitch, even if the child can't yet explain what's off. Build the habit from the start: tuner first, then practice. Our tuner is also free and works through the microphone — a child can manage it independently after being shown a couple of times." },
      { type: "h2", text: "Don't compare with other children" },
      { type: "p", text: "Kids' pace of progress varies a lot, and that's normal. A kui one child learns in a week might take another a month — that's not about ability, just a different pace. Focusing on regular short practice sessions works better than rare, long \"pushes.\"" },
    ],
    tr: [
      { type: "p", text: "Dombra genellikle bir Kazak çocuğunun hayatındaki ilk müzik aletidir — ve burada iyi niyetle yapılan hatalar sık görülür: \"büyüsün diye\" daha büyük bir enstrüman almak, ilk günlerden itibaren dersleri fazla yüklemek veya çok zor bir küy seçmek. Gerçekten nereden başlamak gerektiğine bakalım." },
      { type: "h2", text: "\"Büyüsün diye\" enstrüman almayın" },
      { type: "p", text: "\"Daha uzun süre yetsin\" diye daha büyük bir dombra almak cazip gelir — ama çocuk için genellikle ters teper. Çok büyük bir gövde ve geniş bir sap çalmayı fiziksel olarak zorlaştırır: parmaklar perdelere yetişmez, enstrümanı tutmak zorlaşır. 10-12 yaş altı çocuklar için genellikle 42 ölçü uygundur — katalogdaki en kompakt seçenek." },
      { type: "h2", text: "İlk haftalar teknik değil, ilgi hakkındadır" },
      { type: "p", text: "İlk ayın amacı zor bir küy öğrenmek değil, çalışma isteğini öldürmemektir. Çabuk başarılan basit, tekrarlı ezgiler, teknik olarak doğru ama sıkıcı bir yöntemden daha iyi işe yarar. Çıkardığı sesi beğenen bir çocuk, enstrümanı kendi isteğiyle tekrar eline alacaktır." },
      { type: "h2", text: "Yanında bir yetişkin olmadığında eğitim aracı yardımcı olur" },
      { type: "p", text: "Ebeveynlerin her zaman oturup her hareketi izleyecek vakti olmayabilir. dombyra.kz'deki ücretsiz eğitim aracı, parmakların nereye konacağını çocuğun kendi hızında gösterir — hızı neredeyse yarıya indirip zor bir kısmı gerektiği kadar tekrarlayabilirsiniz. Karaoke modu ise mikrofon aracılığıyla çalışını dinler ve yanlış notaları vurgular — çocuk, yanında düzeltecek biri olmadan kendi ilerlemesini görür." },
      { type: "h2", text: "Dombra akortlu olmalı — bu da çocuğun sorumluluğu" },
      { type: "p", text: "Akortsuz bir enstrüman, çocuk neyin yanlış olduğunu henüz açıklayamasa bile kulağı yanlış bir perdeye alıştırır. Bunu baştan bir alışkanlık haline getirin: önce akort aleti, sonra çalışma. Bizim akort aletimiz de ücretsizdir ve mikrofon aracılığıyla çalışır — birkaç kez gösterildikten sonra çocuk bunu kendi başına yapabilir." },
      { type: "h2", text: "Diğer çocuklarla karşılaştırmayın" },
      { type: "p", text: "Çocukların ilerleme hızı büyük ölçüde değişir ve bu normaldir. Bir çocuğun bir haftada öğrendiği bir küy, başka birine bir ay sürebilir — bu yetenekle ilgili değil, sadece farklı bir tempo. Seyrek ama uzun \"atılımlardan\" ziyade düzenli, kısa çalışmalara odaklanmak daha iyi sonuç verir." },
    ],
  },
};
